version: '3.9'
services:
  wordpress1:
    image: wordpress
    container_name: wordpress1
    env_file:
      - .env
    ports:
      - "8081:80"
    networks:
      - wordpressred
    volumes:
      - ${WORDPRESS_LOCAL_HOME1}:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX1: ${WORDPRESS_TABLE_PREFIX1}
      APACHE-SERVER-NAME: wordpress-backend.com

  wordpress2:
    image: wordpress
    container_name: wordpress2
    env_file:
      - .env
    ports:
      - "8082:80"
    networks:
      - wordpressred
    volumes:
      - ${WORDPRESS_LOCAL_HOME2}:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX2: ${WORDPRESS_TABLE_PREFIX2}
      APACHE-SERVER-NAME: wordpress-backend.com

  wordpress3:
    image: wordpress
    container_name: wordpress3
    env_file:
      - .env
    ports:
      - "8083:80"
    networks:
      - wordpressred
    volumes:
      - ${WORDPRESS_LOCAL_HOME3}:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX3: ${WORDPRESS_TABLE_PREFIX3}
      APACHE-SERVER-NAME: wordpress-backend.com

  base_master:
    image: mysql
    container_name: base_master
    env_file:
      - .env
    networks:
      - wordpressred
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME1}:/var/lib/mysql
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=replica
      #- '--default-authentication-plugin=mysql_native_password'
    
  base_esclavo:
    image: mysql:latest
    container_name: base_esclavo
    env_file:
      - .env
    networks:
      - wordpressred
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME2}:/var/lib/mysql
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=replica
      #- '--default-authentication-plugin=mysql_native_password'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    env_file:
      - .env
    ports:
      - "8080:80"
    networks:
      - wordpressred
    depends_on:
      - base_master
      - base_esclavo
    volumes:
      - ${MYSQL_LOCAL_HOME1}:/var/lib/mysql
      - ${MYSQL_LOCAL_HOME2}:/var/lib/mysql
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ARBITRARY: 1

  nginx:
    image: nginx
    container_name: nginx
    env_file:
      - .env
    ports: 
      - "80:80"
    networks:
      - wordpressred
    volumes:
      - ${WORDPRESS_LOCAL_HOME1}:/var/www/html
      - ${WORDPRESS_LOCAL_HOME2}:/var/www/html
      - ${WORDPRESS_LOCAL_HOME3}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/nginx.conf:ro
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3

networks:
  wordpressred:
    driver: bridge