version: '3.9'
services:
  wordpress1:
    image: wordpress
    container_name: wordpress1
    env_file:
      - .env
    ports:
      - "8081:80"
    networks:
      - wordpressred
    depends_on:
      - database1
    volumes:
      - ${WORDPRESS_LOCAL_HOME1}:/var/www/html
    environment:
      WORDPRESS_DB_HOST1: ${WORDPRESS_DB_HOST1}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      APACHE_SERVER_NAME: wordpress-backend.com

  wordpress2:
    image: wordpress
    container_name: wordpress2
    env_file:
      - .env
    ports:
      - "8082:80"
    networks:
      - wordpressred
    depends_on:
      - database2
    volumes:
      - ${WORDPRESS_LOCAL_HOME2}:/var/www/html
    environment:
      WORDPRESS_DB_HOST2: ${WORDPRESS_DB_HOST2}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      APACHE_SERVER_NAME: wordpress-backend.com

  wordpress3:
    image: wordpress
    container_name: wordpress3
    env_file:
      - .env
    ports:
      - "8083:80"
    networks:
      - wordpressred
    depends_on:
      - database3
    volumes:
      - ${WORDPRESS_LOCAL_HOME3}:/var/www/html
    environment:
      WORDPRESS_DB_HOST3: ${WORDPRESS_DB_HOST3}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      APACHE_SERVER_NAME: wordpress-backend.com

  database1:
    image: mysql
    container_name: database1
    env_file:
      - .env
    ports:
      - "3307:3306"
    networks:
      - wordpressred
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME1}:/var/lib/mysql
    command: 
      - '--default-authentication-plugin=mysql_native_password'
      - '--server-id=1'
      - '--log-bin=mysql-bin'
      - '--binlog-do-db=wordpress'

  
  database2:
    image: mysql
    container_name: database2
    env_file:
      - .env
    ports:
      - "3308:3306"
    networks:
      - wordpressred
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME2}:/var/lib/mysql
    command: 
      - '--default-authentication-plugin=mysql_native_password'
      - '--server-id=2'
      - '--log-bin=mysql-bin'
      - '--binlog-do-db=wordpress'

  database3:
    image: mysql
    container_name: database3
    env_file:
      - .env
    ports:
      - "3309:3306"
    networks:
      - wordpressred
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME3}:/var/lib/mysql
    command: 
      - '--default-authentication-plugin=mysql_native_password'
      - '--server-id=3'
      - '--log-bin=mysql-bin'
      - '--binlog-do-db=wordpress'

  nginx:
    image: nginx
    container_name: nginx
    env_file:
      - .env
    ports: 
      - "8080:80"
    networks:
      - wordpressred
    volumes:
      - ${WORDPRESS_LOCAL_HOME1}:/var/www/html
      - ${WORDPRESS_LOCAL_HOME2}:/var/www/html
      - ${WORDPRESS_LOCAL_HOME3}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/nginx.conf:ro
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3
    
networks:
  wordpressred:
    driver: bridge
